import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/Header/Header";
import Card from "../components/Card/Card";
import axios, { isCancel, AxiosError } from "axios";
import React from "react";

export default function Home() {
  const [movies, setMovies] = React.useState([]);

  React.useEffect(() => {
    axios
      .get("https://api.tvmaze.com/search/shows?q=all")
      .then(function (response) {
        // handle success
        const shows = response.data;
        setMovies(shows);
        console.log(response.data);
      })
      .catch(function (error) {
        // handle error
        console.log(error);
      });
  }, []);

  React.useEffect(() => {
    console.log(`from movies: ${JSON.stringify(movies)}`);
  }, [movies]);

  return (
    <div className="wrapper">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <div className="container">
        {movies.map((movieObj, i) => {
          const movie = movieObj.show;
          return (
            <Card
              imgSrc={movie.image?.original}
              title={movie.name}
              genres={movie.genres}
              rating={movie.rating?.average}
              // description={movie.summary}
              key={movie.id}
              id={i}
            />
          );
        })}
      </div>
      <style jsx>
        {`
          .wrapper {
            width: 100%;
             {
              /* border: 1px solid red; */
            }
          }
          .container {
            display: flex;
            width: 100%;

            margin-top: 50px;
            padding: 0px 10px;
            flex-wrap: wrap;
            row-gap: 40px;
            column-gap: 4%;
            //border: 1px solid red;
          }

          @media screen and (min-width: 900px) {
            .container {
              column-gap: 5%;
            }
          }
        `}
      </style>
    </div>
  );
}
